apiVersion: v1
kind: Service
metadata:
  name: jitti-service
  namespace: jittiapp
  labels:
    app: jittiapp
spec:
  clusterIP: 10.99.112.225
  clusterIPs:
  - 10.99.112.225
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30496
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: jittiapp
  sessionAffinity: None
  type: LoadBalancer
